name: Release on tag push

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Get version from version.txt
        id: version
        run: echo "::set-output name=version::$(cat version.txt)"
      - name: Get previous release tag
        uses: peter-evans/release-branch-convention@v1
        id: get_previous_release
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          name: Pre Release ${{ steps.version.outputs.version }}
          tag: v${{ steps.version.outputs.version }}
          prerelease: true
          draft: false
          body: |
            Changes since ${{ steps.get_previous_release.outputs.previous_tag }}:
            ${{ steps.get_previous_release.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
