name: Auto Deploy

on:
#   push:
#     branches:
#       - main
    workflow_dispatch:
jobs:
  updatedoc:
    runs-on: ubuntu-latest
    steps:
      - name: ドキュメント アップデート
        uses: .github/workflows/updatedoc.yml
