name: Run pytest
on: 
    workflow_dispatch:
    repository_dispatch:
        types:
        - pytest
    workflow_call:
    push:
        branches:
        - develop

jobs:
  pytest:
    strategy:
      matrix:
        python-version: [3.9.15, 3.10.12, 3.11.4]

    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Checkout
        uses: actions/checkout@v2

      # Pythonの環境をセットアップ
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # pytestをインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          pip install -r requirements.txt

      # pytest -> JUnit xml形式で結果を出力
      - name: PyTest
        run: |
          export PYTHONPATH=./repos/
          pytest tests --junit-xml results/pytest.xml --disable-warnings --cov=repos/ --cov-report=term-missing:skip-covered | tee results/pytest-coverage.txt
        continue-on-error: true

      # テスト結果の表示
      # - name: Upload Unit Test Results
      #   if: ${{ always() }}
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: Unit Test Results (Python ${{ matrix.python-version }})
      #     path: results/*.xml

      # - name: Download Artifacts
      #   if: success() || failure()
      #   uses: actions/download-artifact@v2
      #   with:
      #     path: artifacts

      # - name: Publish Unit Test Results
      #   uses: EnricoMi/publish-unit-test-result-action@v2
      #   with:
      #     junit_files: artifacts/**/*.xml

      - name: Print time
        run: |
          echo "This is Python ${{ matrix.python-version }} summary!" >> $GITHUB_STEP_SUMMARY
      
      - name: Pytest coverage comment
        # if: ${{ steps.is_main.outputs.flag == '1' }}
        id: coverageComment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          hide-comment: true
          pytest-coverage-path: ./results/pytest-coverage.txt
          junitxml-path: ./results/pytest.xml

      - name: Write job summary
        id: check_status
        run: |
          echo -e ${{ steps.coverageComment.outputs.summaryReport }} >> $GITHUB_STEP_SUMMARY
          cat ./results/pytest-coverage.txt >> $GITHUB_STEP_SUMMARY
    