name: Auto Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
    version-increment:
        uses: ./.github/workflows/version_increment.yml
    update-docs:
        uses: ./.github/workflows/updatedoc.yml
    deploy-prod:
        uses: ./.github/workflows/deploy_prod.yml
    update-tag:
        uses: ./.github/workflows/tag_update_prod.yml
    # merge-develop:
    #     uses: ./.github/workflows/merge_to_develop.yml


