name: Auto Deploy

on:
#   push:
#     branches:
#       - main
    workflow_dispatch:
jobs:
    call-workflow:
        name: Update Docs
        runs-on: ubuntu-latest
        permissions:
          contents: write
          checks: write
          pull-requests: write
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: call workflow
              uses: ./.github/workflows/updatedoc.yml


