name: Auto Deploy

on:
#   push:
#     branches:
#       - main
    workflow_dispatch:
jobs:
    call-workflow:
        step:
          - uses: actions/checkout@v3
          uses: .github/workflows/updatedoc.yml

