name: Auto Deploy

on:
    push:
        branches:
            - main
    pull_request:
        types: [closed]
    workflow_dispatch:
jobs:
    # version-increment:
    #     uses: ./.github/workflows/version_increment.yml
    update-docs:
        uses: ./.github/workflows/updatedoc.yml
    merge-develop:
        uses: ./.github/workflows/merge_to_develop.yml


