name: Auto Deploy

on:
    # push:
    #     branches:
    #         - main
    pull_request:
        types: [closed]
    workflow_dispatch:
jobs:
    # version-increment:
    #     uses: ./.github/workflows/version_increment.yml
    update-docs:
        # needs: version-increment
        uses: ./.github/workflows/updatedoc.yml
    deploy-prod:
        needs: update-docs
        uses: ./.github/workflows/deploy_prod.yml
        secrets:
            PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
    update-tag:
        needs: deploy-prod
        uses: ./.github/workflows/tag_update_prod.yml
    merge-develop:
        needs: update-tag
        uses: ./.github/workflows/recreate_develop_branch.yml
