name: Deploy Prod
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      PYPI_TOKEN:
        required: true
jobs:
  release:
    name: Deploy Prod
    runs-on: ubuntu-latest
    permissions:
      contents: write
      checks: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          git pull
          pip install --upgrade setuptools wheel twine

      - name: Build package
        run: python setup.py sdist bdist_wheel

      - name: Publish to pypi.org
        run: |
          echo "[distutils]
          index-servers =
              pypi

          [pypi]
          repository = https://upload.pypi.org/legacy/
          username = __token__
          password = ${PYPI_TOKEN}" > ~/.pypirc
          twine upload --repository pypi dist/*
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
