name: Merge to develop

on:
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_call:

jobs:
  merge:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: test
        run: |
          git fetch
          git branch -a
        
      - name: Merge to develop
        run: |
          git config user.email "dummy@dummy"
          git config user.name "github-actions"
          git checkout develop
          git merge main --allow-unrelated-histories
          # マージコミットの作成とプッシュ
          git commit -m "Merge main into develop" --allow-empty
          git push origin develop
