name: Release on tag push

on:
  push:
    branches: [ main ]
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get current tag
        run: |
          TAG=$(cat version.txt)
          echo "::set-output name=tag::$TAG"
        id: get_tag
      - name: Create release
        uses: peter-evans/create-pull-request@v3.11.0
        with:
          commit-message: 'chore: release ${{ steps.get_tag.outputs.tag }}'
          title: 'chore: release ${{ steps.get_tag.outputs.tag }}'
          body: |
            ${{ steps.diff.outputs.changelog }}
          branch: 'main'
          base: 'main'
          draft: true
          labels: 'pre-release'
      - name: Get changelog
        uses: dorny/paths-filter@v2.1.0
        with:
          filters: |
            CHANGELOG.md
        id: changelog
      - name: Get diff
        id: diff
        run: |
          echo -e "# Changelog\n\n$(git --no-pager diff --name-only $(git describe --tags --abbrev=0) HEAD -- CHANGELOG.md | awk '{printf("- [%s](https://github.com/USER/REPO/commit/%s)\n", $0, $0)}')" > changelog.md
          echo "::set-output name=changelog::$(cat changelog.md)"
      - name: Commit changelog
        uses: EndBug/add-and-commit@v7
        with:
          message: 'docs: update changelog [skip ci]'
          add: 'changelog.md'
