name: Release on tag push

on:
  push:
    branches: [ main ]
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      checks: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get current tag
        run: |
          TAG=$(cat version.txt)
          echo "::set-output name=tag::$TAG"
        id: get_tag
      - name: Get changelog
        uses: dorny/paths-filter@v2.1.0
        with:
          filters: |
            paths:
              - CHANGELOG.md
      - name: Get diff
        id: diff
        run: |
          echo -e "# Changelog\n\n$(git --no-pager diff --name-only $(git describe --tags --abbrev=0) HEAD -- CHANGELOG.md | awk '{printf("- [%s](https://github.com/flarebrow/flaretool/commit/%s)\n", $0, $0)}')" > CHANGELOG.md
          echo "::set-output name=changelog::$(cat CHANGELOG.md)"
          echo "# Changelog\n\n$(git --no-pager diff --name-only $(git describe --tags --abbrev=0) HEAD -- CHANGELOG.md | awk '{printf("- [%s](https://github.com/flarebrow/flaretool/commit/%s)\n", $0, $0)}')"
      - name: Commit changelog
        uses: EndBug/add-and-commit@v7
        with:
          message: 'docs: update changelog [skip ci]'
          add: 'CHANGELOG.md'
        id: changelog
      - name: Create release
        uses: peter-evans/create-pull-request@v3.11.0
        with:
          commit-message: 'chore: release ${{ steps.get_tag.outputs.tag }}'
          title: 'chore: release ${{ steps.get_tag.outputs.tag }}'
          body: |
            ${{ steps.diff.outputs.changelog }}
          branch: 'release'
          base: 'main'
          draft: true
          labels: 'pre-release'
      - name: Create Release2
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d "{ \"tag_name\": \"v${{ steps.get_tag.outputs.tag }}\", \"name\": \"Pre Release v${{ steps.get_tag.outputs.tag }}\", \"body\": \"${{ steps.release_note.outputs.release_note }}\"}" \
            https://api.github.com/repos/${{ github.repository }}/prereleases